"""Phase 3 gate: rejected content never renders, and rejections are durable.

The asymmetry with corrections is the whole of this file. A correction is an
**assertion** — the user says the dose was 5mg, not 50mg — so the superseded
reading stays visible and the assertion can be checked against it. A rejection is
a **retraction**, and printing the content re-asserts what the user said is not
true of them.

The deciding case is that this record gets printed and handed to a clinician.
Someone who rejects a mis-OCR'd "alcohol dependence" must not find it on their
problems page under any heading, however carefully that heading is worded.

The durability half is the same failure class as a correction being reintroduced
by a later model read, so it is tested the same way: in both event orderings. The
gate keyed on the target claim's id, and a re-extraction produces a new id, so
nothing suppressed the second reading. At low consequence it did not even wait to
be asked — it applied itself to the wiki.
"""

from __future__ import annotations

import pytest

from agent import projection

from .conftest import claim, confirm, ingested, reject, on_day

DEVICE = "laptop-a1b2"
AS_OF = "2026-09-30T00:00:00Z"

#: Low consequence on purpose: it auto-applies, so nothing but the suppression
#: stands between a rejected reading and the wiki.
SUBJECT = "person:dr-nguyen"
PREDICATE = "note"
REJECTED_TEXT = "said the patient drinks heavily"


def _project(events):
    return projection.project(sorted(events, key=lambda e: e.sort_key), AS_OF)


def _reading(day: int, text: str = REJECTED_TEXT, artifact: str = "a3f91c"):
    return claim(DEVICE, SUBJECT, PREDICATE, text, ts=on_day(day), artifact=artifact)


def _assert_absent(result, text: str = REJECTED_TEXT):
    """The rule, stated as strongly as it can be: not in any generated byte."""
    for rel, body in result.files.items():
        assert text.encode("utf-8") not in body, f"rejected content rendered in {rel}"
        assert b"Rejected" not in body, f"a rejected section appeared in {rel}"


def test_a_rejected_reading_appears_in_no_generated_file():
    first = _reading(2)
    result = _project([ingested(DEVICE), first, reject(DEVICE, first.id, ts=on_day(3))])

    _assert_absent(result)
    assert result.entities == {}


@pytest.mark.parametrize("reproposal_day, rejection_day", [(9, 3), (1, 3)])
def test_re_extraction_does_not_resurrect_a_rejection(reproposal_day, rejection_day):
    """Both orderings, because a shard from another device can sort either way.

    The suppression is built from the whole log before anything is admitted, so
    a re-extraction that lands *before* the rejection is suppressed too.
    """
    first = _reading(2)
    again = _reading(reproposal_day)
    result = _project(
        [ingested(DEVICE), first, reject(DEVICE, first.id, ts=on_day(rejection_day)), again]
    )

    _assert_absent(result)
    assert result.entities == {}
    # Nor does it come back as something to decide again.
    assert result.review == ()


def test_a_reformatted_re_extraction_is_still_the_same_claim():
    """Compare the normalised: `5.0mg daily` is the reading that was rejected."""
    first = claim(DEVICE, "med:perindopril", "dose", "5mg daily", ts=on_day(2))
    again = claim(DEVICE, "med:perindopril", "dose", "5.0mg daily", ts=on_day(9))
    result = _project(
        [ingested(DEVICE), first, reject(DEVICE, first.id, ts=on_day(3)), again]
    )

    assert result.entities == {}
    assert result.review == ()


def test_confirming_a_re_proposal_is_how_the_user_says_otherwise():
    """Suppression is durable, not permanent. A decision on the claim itself wins."""
    first = _reading(2)
    again = _reading(9)
    result = _project(
        [
            ingested(DEVICE),
            first,
            reject(DEVICE, first.id, ts=on_day(3)),
            again,
            confirm(DEVICE, again.id, ts=on_day(10)),
        ]
    )

    entity = result.entities[SUBJECT]
    assert entity.slots[PREDICATE].winner.value.literal == REJECTED_TEXT


def test_saying_otherwise_lifts_the_suppression_for_later_re_extractions_too():
    """"Until the user says otherwise" is about the reading, not one claim id.

    Once the user has confirmed this reading, a further re-extraction of it is
    not a resurrection of something they retracted — it is more evidence for
    something they accepted, and dropping it would quietly age the entry.
    """
    first, again, third = _reading(2), _reading(9), _reading(20)
    result = _project(
        [
            ingested(DEVICE),
            first,
            reject(DEVICE, first.id, ts=on_day(3)),
            again,
            confirm(DEVICE, again.id, ts=on_day(10)),
            third,
        ]
    )
    slot = result.entities[SUBJECT].slots[PREDICATE]

    assert slot.winner.event_id == third.id
    assert {c.event_id for c in slot.all_claims} == {again.id, third.id}


def test_a_later_rejection_suppresses_again():
    """The rule reads the user's most recent word, in either direction."""
    first, again, third = _reading(2), _reading(9), _reading(20)
    result = _project(
        [
            ingested(DEVICE),
            first,
            confirm(DEVICE, first.id, ts=on_day(3)),
            again,
            reject(DEVICE, again.id, ts=on_day(10)),
            third,
        ]
    )
    slot = result.entities[SUBJECT].slots[PREDICATE]

    # The claim they explicitly confirmed still stands — declining to honour a
    # user's tap is not something the projection may do on its own — but the
    # undecided re-extraction does not come back.
    assert {c.event_id for c in slot.all_claims} == {first.id}


def test_a_second_artefact_saying_the_same_thing_is_new_evidence():
    """The artefact is in the key on purpose.

    The user decided about one reading of one document. A different document
    saying the same thing has not been decided, and suppressing it would let one
    rejection silently blind the record to a whole class of evidence.
    """
    first = _reading(2)
    elsewhere = _reading(9, artifact="77b210")
    result = _project(
        [
            ingested(DEVICE, "a3f91c"),
            ingested(DEVICE, "77b210"),
            first,
            reject(DEVICE, first.id, ts=on_day(3)),
            elsewhere,
        ]
    )

    entity = result.entities[SUBJECT]
    assert entity.slots[PREDICATE].winner.event_id == elsewhere.id
    assert entity.sources == ("77b210",)


def test_an_all_rejected_artefact_is_reviewed_not_unprocessed():
    """Phase 7 must not put it back in the inbox as though nothing had read it."""
    first = _reading(2)
    second = claim(DEVICE, SUBJECT, "role", "cardiologist", ts=on_day(2, hour=10))
    result = _project(
        [
            ingested(DEVICE),
            first,
            second,
            reject(DEVICE, first.id, ts=on_day(3)),
            reject(DEVICE, second.id, ts=on_day(3, hour=10)),
        ]
    )

    review = result.artifacts["a3f91c"]
    assert review.claims == 2
    assert review.rejected == 2
    assert review.is_reviewed is True
    assert review.all_rejected is True
    assert result.review == ()
    assert result.stats()["artifacts_reviewed"] == 1
    assert result.stats()["artifacts_awaiting_review"] == 0


def test_an_undecided_artefact_is_still_awaiting_review():
    """The other half of the distinction, so `is_reviewed` means something."""
    result = _project([ingested(DEVICE), _reading(2)])

    assert result.artifacts["a3f91c"].is_reviewed is False
    assert result.stats()["artifacts_awaiting_review"] == 1
